id = "matte-black"
name = "Matte Black"
version = "1.1.3"
schema_version = 1
authors = ["Taha YVR <taha@noiserandom.com>"]
description = "A low-distraction dark theme for Zed."
repository = "https://github.com/tahayvr/matte-black-zed"
